# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MCU_Acceptance.xdc

# IP: ip/dist_mem_gen_1/dist_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_1 || ORIG_REF_NAME==dist_mem_gen_1} -quiet] -quiet

# IP: ip/data_out_mem/data_out_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_out_mem || ORIG_REF_NAME==data_out_mem} -quiet] -quiet
